### ISSUE TITLE
btop consistently reports cpu at max frequency

### ISSUE THREAD

**Issue by theofficialgman** [aristocratos/btop#143]
**Describe the bug**

Using btop the cpu frequency reported is almost always the maximum frequency (the act of reading the cpu frequency from the file is causing the cpu to boost momentarily). 

https://github.com/aristocratos/btop/blob/156998073a9710a288fcb6ca8fe4fee226b04bc4/src/linux/btop_collect.cpp#L363

this doesn't seem to be the case with htop which is not causing my cpu to boost.

https://github.com/htop-dev/htop/blob/d8dfbbd37ca7855be44391697424edac9015f14f/linux/LinuxProcessList.c#L1989

for reference doing a `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq` also causes the output to be the maximum frequency most of the time as well.
Maybe this is btop just being heavier than htop, but I think it could also just as easily be how the file is read with `readfile`

**To Reproduce**

Open btop and observed the frequency in the top corner. Frequency is almost always fount to be the maximum cpu frequency.

**Expected behavior**

Frequency should scale with cpu load.

**Screenshots**

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - btop++ version: v1.0.23
 - Binary: static binary from release
 - Architecture: aarch64
 - Platform: linux
 - (Linux) Kernel: 4.9.140+
 - Terminal used: bash 4.4.20

**Comment by aristocratos** [comment]
@theofficialgman 
`readfile` just does a standard `getline()` so shouldn't be heavier than any other file read operation.

https://github.com/aristocratos/btop/blob/0201b5f859c530f8382a74e47e93c85c5ca7d4f1/src/btop_tools.cpp#L360-L372

But this is likely caused by the "collector" for the cpu box being run last, and the "collector" for the processes will likely push up the frequency before the file have been read. I don't get this issue on a Pinebook Pro (the only arm cpu I have to test on), but I guess it would be different on for example older raspberry pi's.

If you want, could you test moving the order around by moving the `CPU` block on line 478-496 to above the `PROC` block on line 417 in btop.cpp?

**Comment by aristocratos** [comment]
@theofficialgman 
Pushed a commit with some reordering since the current order was based on the use of async threads which was removed a while back. So you can try a binary from the latest continuous build and see if it makes any difference.

**Comment by theofficialgman** [comment]
> @theofficialgman Pushed a commit with some reordering since the current order was based on the use of async threads which was removed a while back. So you can try a binary from the latest continuous build and see if it makes any difference.

@aristocratos works as I would expect this new way. I've been testing on nintendo switch (tegra x1, A57 cores up to 2.091ghz) with the schedutil governor. I assume its just very reactive to changes in load and is fast to boost frequency
