### ISSUE TITLE
[BUG] btop doesn't like QEMU

### ISSUE THREAD

**Issue by scottjl** [aristocratos/btop#157]
running btop on ubuntu 18.04 server with several qemu vm's running, getting the following spewed to error non-stop:

```
Unknown host QEMU_IFLA type: 47
Unknown host QEMU_IFLA type: 48
Unknown host QEMU_IFLA type: 43
Unknown QEMU_IFLA_BRPORT type 28
Unknown QEMU_IFLA_BRPORT type 27
Unknown QEMU_IFLA_BRPORT type 30
Unknown QEMU_IFLA_BRPORT type 29
Unknown QEMU_IFLA_BRPORT type 31
Unknown QEMU_IFLA_BRPORT type 32
```

just keeps repeating those lines over and over.

**Comment by aristocratos** [comment]
@scottjl 
I would suggest you remake this report using the bug report template since you have given no useable information to actually debug this. 

You are getting errors somewhere (btop logfile?, terminal?, syslog?) when running some version(?) of btop (and or inside?) qemu on a unknown architecture(?). 

And googling those errors links to issues related to qemu, so not sure why you think this would be a bug in btop?

**Comment by scottjl** [comment]
well since it was on ubuntu 18.4, most people would naturally assume it was on intel. it certainly wasn't on a z80 chip. as i said, it was spewed to error, i redirected the output with 2> to a log file. the latest version of btop, because i have no reason to run an old version.

might be related to an issue with qemu, i don't know, but it came out of btop when ran btop and not from dmesg or my system.

rather than waste more of my time investigating your application i'll just uninstall it. problem solved for me!

**Comment by aristocratos** [comment]
@scottjl 
> well since it was on ubuntu 18.4, most people would naturally assume it was on intel.

Why? And Intel span multiple architectures.

> might be related to an issue with qemu, i don't know, but it came out of btop when ran btop and not from dmesg or my system.

Again, googling your errors links to multiple qemu issues you should maybe look at if you actually wanna fix the issue. Since these are not any errors btop on it's own would generate.

> rather than waste more of my time investigating your application i'll just uninstall it. problem solved for me!

Sure, limiting what software you can run and avoiding the problem is one solution...

**Comment by scottjl** [comment]
> Sure, limiting what **_buggy_** software you can run and avoiding the problem is one solution...

FIFY. i'm out.

**Comment by aristocratos** [comment]
@scottjl 

> > Sure, limiting what buggy software you can run and avoiding the problem is one solution...
> 
> FIFY. i'm out.

Not sure you've noticed but this is a open source community and not your personal support page, fixing issues is a collaborative effort and won't get far when you're unwilling to do basic stuff like filling in a bug report template.

I don't really care if you use this software or not, after all it's "free". But calling this software "buggy" because of a likely issue in some other software as some kind of insult speaks more to your level of maturity then anything else...
