### ISSUE TITLE
[BUG] CPU section incorrect rendering on Konsole

### ISSUE THREAD

**Issue by cyqsimon** [aristocratos/btop#202]
## Description

On Konsole terminal, CPU core usage & temp readouts are incorrectly positioned and often obstructed by their unit symbols.

Alacritty seems to be unaffected. I haven't tested any other terminal emulator.

At most terminal sizes there is some kind of obstruction, although the exact behaviour of the obstruction varies.

## To reproduce

- Load the CPU with `stress` or any other tool
- Run btop in Konsole to see the obstruction

### As tested on Fedora VM
![On Fedora](https://user-images.githubusercontent.com/28627918/145738251-2aaff10c-7d95-46c1-b910-8c9aebd40b69.png)
C2 should be 100%, not 10%.
Also note that the CPU model should be `i7-10710U`, but that's a separate issue that seems to be Fedora-specific.

### As tested on Manjaro physical
![On Manjaro](https://user-images.githubusercontent.com/28627918/145738504-c2f692cb-3214-48f9-9fc7-d6b96fe4d263.png)
Both core usage and temperature are messed up.

## Info
 - btop++ version: 1.1.3
 - Binary: both release and compiled
 - Compiler and version: Fedora: `gcc 11.2.1`, Manjaro: `gcc 11.1.0`
 - Architecture: x86_64
 - Platform: Linux
 - (Linux) Kernel: Fedora: `5.15.6-200.fc35.x86_64`, Manjaro: `5.4.163-1-MANJARO`
 - Terminal used: Konsole (and by extension Yakuake, since it embeds Konsole)
 - Font used: basically all* (tested: Monospace, Andale Mono, Courier New, Droid Sans, Incosolata, Liberation, Noto, Source Code)

\* Curiously, Iosevka fonts seem to be bug-free.

**Comment by RedBearAK** [comment]
I can't say for certain that this is the same thing, but BashTOP and BPyTOP (the previous iterations of BTOP) had a long-standing issue with the way that Konsole treats certain characters. Usually to fix this you need to change the font used in Konsole, or somehow fix the font setup on your machine. Try looking through this thread in the BPyTOP issues to see if there is a fix you can implement: 

https://github.com/aristocratos/bpytop/issues/100

You'll notice in one of your screenshots that the graph symbols are becoming misaligned. This is the same font issue and pretty much only happens on Konsole. 

>  Also note that the CPU model should be i7-10710U, but that's a separate issue that seems to be Fedora-specific.

The full CPU name can't display in one of the screenshots because the core temps are not being displayed in the CPU box, either because they are disabled in options or there is no info about core temps on that system (Probably because it's a VM?). That shrinks the CPU box down quite a bit, and limits the number of characters of the CPU name that can be displayed. 

The "Manjaro physical" screenshot of course shows the core temps and thus has plenty of room to display the whole CPU name.

**Comment by aristocratos** [comment]
@cyqsimon 
Read the README.md, konsole is even specifically named: [Prerequisites (Read this if you are having issues!)](https://github.com/aristocratos/btop#prerequisites)

**Comment by cyqsimon** [comment]
My apologies. I missed that part in README and a search in issues turned up nothing.

Turning off bidirectional text rendering did solve the issue, thank you.

**Comment by Nephyrin** [comment]
I believe this MR fixed this upstream in konsole:
https://invent.kde.org/utilities/konsole/-/merge_requests/524
