### ISSUE TITLE
[BUG] OsX terminal wrong background colors

### ISSUE THREAD

**Issue by doj** [aristocratos/btop#281]
** description **

I've used homebrew on OsX to install btop. I'm using the standard OsX terminal program, using a white background. btop seems to run fine, but in windows with the graphs seems to set the background color of the characters to non-white. This results in large bars of green, yellow, red, etc. The font color seems to be light gray. Please see the attached screenshot.

When I select a terminal color scheme with black background, btop seems to have the same issue. The background color of characters is set, while the font color stays light gray.

**Expected behavior**

I would expect the font color to be set, and the background color to either stay the default, or force all background color to be black.

**Screenshots**

![Screen Shot 2022-02-28 at 9 03 33 AM](https://user-images.githubusercontent.com/198352/156031184-f474e9ee-3c99-4e93-b21c-db540767acc6.png)

![Screen Shot 2022-02-28 at 9 33 09 AM](https://user-images.githubusercontent.com/198352/156031201-17a95393-d889-468f-a073-d9dc0c730000.png)

**Info (please complete the following information):**
 - btop++ version: btop version: 1.2.4
 - Binary: homebrew package
 - (If compiled) Compiler and version:
 - Architecture: [x86_64, aarch64, etc.] `uname -m`
 - Platform: OsX
 - (OSX/FreeBSD) Os release version: OsX 12.2.1
 - Terminal used: xterm-256color
 - Font used: don't know

**Additional context**

2022/02/28 (09:36:20) | ===> btop++ v.1.2.4
2022/02/28 (09:36:20) | DEBUG: Starting in DEBUG mode!
2022/02/28 (09:36:20) | INFO: Logger set to DEBUG
2022/02/28 (09:36:20) | DEBUG: Using locale en_US.UTF-8
2022/02/28 (09:36:20) | INFO: Running on /dev/ttys000
2022/02/28 (09:36:20) | DEBUG: get_sensors(): show_coretemp=1 check_temp=1
2022/02/28 (09:36:20) | DEBUG: checking intel
2022/02/28 (09:36:20) | DEBUG: intel sensors found
2022/02/28 (09:36:20) | DEBUG: intel sensors with offset 1
2022/02/28 (09:36:23) | INFO: Quitting! Runtime: 00:00:03

**Comment by aristocratos** [comment]
@doj 
You obviously didn't read https://github.com/aristocratos/btop#prerequisites which is also mentioned in the first lines of the bug report template you used...

> 256-color terminals are supported through 24-bit to 256-color conversion when setting "truecolor" to False in the options or with "-lc/--low-color" arguments.

**Comment by doj** [comment]
you are right, when I set truecolor=False I see good color output, with a black background.
But maybe this should be automatic, when the terminal reports itself as a xterm-256color and not require a manual change to the configuration file?

**Comment by aristocratos** [comment]
@doj 
The issue is that most terminals regardless of actual color capabilities reports `xterm` or `xterm-256color` by default.
So I can't really be used as a indicator.
And I have never seen the TERM reported as `xterm-truecolor` or similar, so that would mean that btop wouldn't show truecolor for _any_ terminal.

And as far as I know, there is no sure and portable way to determine color capabilities.
The issue is however pretty limited since many terminal emulators that doesn't support truecolor, does have builtin conversion from truecolor to 256-color.

Why macos builtin terminal still doesn't have that (or truecolor support) is beyond me...

But I would recommend https://iterm2.com/ for macos, it has full truecolor capability and is in general just a better terminal emulator.
