### ISSUE TITLE
[BUG] btop.conf is overwritten at shutdown. 

### ISSUE THREAD

**Issue by RubyRubenstahl** [aristocratos/btop#282]
If the btop.conf is edited while btop is running, it will be overwritten when btop closes, causing changes to be lost. 

In additon, changes made from within btop could be lost in the event of a crash. 

- btop version: 1.2.4
- build: btop-x86_64-linux-musl
- platform: x86 Ubuntu linux

**Comment by aristocratos** [comment]
@RubyRubenstahl 
It's by design, and only overwrites the config if you changed any setting in the program.
Not sure why you expected external changes to be preserved?

The alternative would be writing to disk every time a hotkey is pressed.
And to not overwrite any changes the config file would have to be continuously monitored and have external changes applied to not get conflicting settings from memory and config file.

Can't honestly say I know any similar programs that implements this functionality.
Probably for good reason since it would be very IO intensive for very little gain.
