### ISSUE TITLE
[REQUEST] CPU and GPU features

### ISSUE THREAD

**Issue by RedDofamine** [aristocratos/btop#300]
The big advantage of the program will be the display of the load on the graphics processors (integrated / external), and the allocated memory. However, the switch between GPUs for all processes or selected (with the ability to save the settings in the configuration file) will be able to select the program above all similar ones, which will make this program not only a monitor but also a tool. This tool also provides for the allocation of a certain number (cores / threads) of the CPU for a particular process tree. This will also create a need for a manual that will describe the flags of certain functions for use from the terminal.

**Comment by godalming123** [comment]
It would be nice to know progress on this as GPU support is the new feature in the next major version (v1.3)

**Comment by aristocratos** [comment]
@godalming123 
No progress is being done on this request since it's wildly out of the aims of this project.
@RedDofamine should probably try to find a tool designed for what he/she wants to do rather than requesting a general purpose system monitor be changed to specialize in load balancing cpu and gpu for processes.

Regarding GPU support for version 1.3, I'm the only one working on btop++ and currently I've taken a detour with #290.
However, a lot of small improvements to the code including the beginnings of GPU support for Nvidia cards have been made during the development of `btop4win` which I will bring over to regular `btop++` when it's done.
