### ISSUE TITLE
If I use `~` in place for theme path, btop does not load the theme

### ISSUE THREAD

**Issue by SichangHe** [aristocratos/btop#309]
**Describe the bug**

btop could not apply the theme placed in `~/.config/btop/themes` if I have this in the config:

```toml
color_theme = "~/.config/btop/themes/<theme name>.theme"
```

But btop *could* apply the theme if I have the full path in my config:

```toml
color_theme = "/<home directory>/.config/btop/themes/<theme name>.theme"
```

**To Reproduce**

1. Copy a btop theme `<theme name>.theme` (cannot be the default theme) and place it in `~/.config/btop/themes`
1. put this in `~/.config/btop/btop.conf`:

    ```toml
    color_theme = "~/.config/btop/themes/<theme name>.theme"
    ```

1. start btop and notice that you are using the default theme as oppose to the theme you specified

**Expected behavior**

btop should use the theme specified

**Info (please complete the following information):**
 - btop++ version: 1.2.5
 - Binary, Architecture, Platform, Kernel:
     this happens on aarch64 macOS Homebrew (macOS 12.0.1)
    and on x86_64 Archlinux pacman (5.13.0-35-generic)
    *but not on x86_64 Ubuntu snap* (5.17.1-arch1-1)
 - Terminal used: kitty
 - Font used: JetBrains Mono

I also ran with `--debug` but nothing suspicious was in the log.

**Comment by aristocratos** [comment]
@SichangHe 
This is expected behavior since the `~` symbol is expanded by your shell, not by btop, same as a shell variable `$VAR` wouldn't work.

You can however just enter the filename of the theme file without the path. Unless the filename is conflicting with a theme in `usr/share/btop/themes` it will work. It will search both the user theme folder and global theme folder for the theme.

Or use the full path.

**Comment by SichangHe** [comment]
I see.
So
## solution
***just use the filename of the theme***
