### ISSUE TITLE
[REQUEST] Please add "?" as an option to see help

### ISSUE THREAD

**Issue by ZiViZiViZ** [aristocratos/btop#325]
I know that when using VIM keys `shift`+`h` can achieve the same thing but I just feel like `?` could be a better alternative.

I like the fact that `shift`+`k` is required since it make it harder to kill by accident.  However, I think getting help should have an easier keybinding.

**Comment by NavigationHazard** [comment]
isn't the default key for us ansi layout "shift + /" in order to execute "?"

**Comment by rebircsbus** [comment]
I agree about `shift`+`/` being easier (also, IMO, more intuitive) since `h` is almost at the center of the keyboard while `/` and `shift` are one besides the other.
However, I wonder how others would feel about this.  If there is a way to change the default keybindings I wouldn't mind just doing that instead.

**Comment by NavigationHazard** [comment]
so the request could be changed into "Add function to remap keybindings" instead.

**Comment by ZiViZiViZ** [comment]
Sorry I prefer this issue to stay as is so the default will change.  If you want to a new feature "ability to remap keybindings" made open another issue for that specific feature.
