### ISSUE TITLE
[RFE]: please use some standard build framework

### ISSUE THREAD

**Issue by kloczek** [aristocratos/btop#355]
Instead using set of custom Makefile files it would be good to move to some standard framework.
IMO the bezst is meson.

**Comment by kloczek** [comment]
Issues with current custom Makefile files:
- hardcoding optimisations flags (injection of -flto=<num> breaks -flto-partition=none which is necessary to use because still some gcc unresolved issues)
- hardcoding strip binaries on install (looks like STRIP=false does not help)
- current Makefile files do not care about $CC, CXX, $LDFLAG, $CFLAGS, $CXXFLAGS env variables

**Comment by aristocratos** [comment]
> hardcoding optimisations flags (injection of -flto= breaks -flto-partition=none which is necessary to use because still some gcc unresolved issues)

It should be apparent if you knew how `make` works that the flags aren't hardcoded. Use `OPTFLAGS=` in the call to make to set it to anything you like.

> hardcoding strip binaries on install (looks like STRIP=false does not help)

This is also not true, the only time the `-s` flag will be appended is if `STRIP=true`. Can very easily be verified by just looking at the Makefile:

https://github.com/aristocratos/btop/blob/102b6dbc9d33906319e7c710cf58ba2893d6ec49/Makefile#L52-L54

> current Makefile files do not care about $CC, CXX, $LDFLAG, $CFLAGS, $CXXFLAGS env variables

Only CXX, CXXFLAGS and LDFLAGS are ignored from environment. But can easily still be set while calling make. Can easily even be directed to your environment variables if you so like by calling `make CXX="$CXX" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS"`.


Instead of asking for replacement of the build system because you don't understand how the current one works,
ask for help or spend some time reading up on how `make` and Makefiles work.


Also addressed in #127

**Comment by eli-schwartz** [comment]
> It should be apparent if you knew how `make` works that the flags aren't hardcoded. Use `OPTFLAGS=` in the call to make to set it to anything you like.

It's true that they are not hardcoded. That being said, they are also not standard, so it might take a bit of work to actually figure out the right way to handle it. And it's pretty common for the various variables to be respected in the *environment*, not just when passed as operands to the `make` utility.

I'll admit to being pleasantly surprised that `make help` actually exists, and in fact points to `make info` which describes what flags are used.

(Using a common build system would still allow people to figure that out more easily, enable persistence in the settings, and reduce the need to maintain that sort of info. But it's not a baseline requirement as long as the Makefile is put together correctly.)

**Comment by aristocratos** [comment]
@eli-schwartz 
Sure, it's not standard, but it's setup to be as beginner-friendly as possible (while also looking good) :)
So that anyone should theoretically be able to install gcc, run `make`, understand what is happening and have a working binary.

Granted, I could write up some more information in the README about how the Makefile is structured and add warnings about which variables will be ignored from environment and how to set them if need be.

But I have to say I get a bit annoyed with requests like this one from OP, where someone encounters a problem and instead of reading up on how the available tools actually work, (or ask for help), just assumes it's not possible because they don't know how it's done. And then suggests some other tool (cmake, ninja, meson)...

The fact of the matter is, btop++ is a very simple project in terms of dependencies. The only needed external dependencies should already be available if you got `gcc` installed properly.
There is no need for advanced build systems like (cmake, meson, etc) that were created to lessen the tedious task of compiling a multitude of external dependant projects.

I would argue it's simple enough that you could manually compile the project without any build system in a couple of minutes if you really felt like it.

And people are still welcome to add compatibility for other build systems, as long as they can co-exist and not replace the Makefile that will work perfectly fine for 99% of people.
