### ISSUE TITLE
[BUG] way too much cores

### ISSUE THREAD

**Issue by bphd** [aristocratos/btop#445]
![image](https://user-images.githubusercontent.com/10251866/195513432-81b078de-8c99-46c7-adc1-02c7191df8b3.png)

**Read the README.md and search for similar issues before posting a bug report!**

# Yes

Any bug that can be solved by just reading the [prerequisites](https://github.com/aristocratos/btop#prerequisites) section of the README will likely be ignored.

**Describe the bug**

# Way too much cores

[A clear and concise description of what the bug is.]

**To Reproduce**

# Run

[Steps to reproduce the behavior:]

**Expected behavior**

# Not way too much cores

[A clear and concise description of what you expected to happen.]

**Screenshots**

# See up

[If applicable, add screenshots to help explain your problem.]

**Info (please complete the following information):**
 - btop++ version: `btop -v`
 - Binary: [self compiled or static binary from release]
 - (If compiled) Compiler and version:
 - Architecture: [x86_64, aarch64, etc.] `uname -m`
 - Platform: [Linux, FreeBSD, OsX]
 - (Linux) Kernel: `uname -r`
 - (OSX/FreeBSD) Os release version:
 - Terminal used:
 - Font used:

# Latest arch; latest community; all default; all terminals; x64

**Additional context**

# No

contents of `~/.config/btop/btop.log`

(try running btop with `--debug` flag if btop.log is empty)

**GDB Backtrace**

# No crash

If btop++ is crashing at start the following steps could be helpful:

(Extra helpful if compiled with `make OPTFLAGS="-O0 -g"`)

1. run (linux): `gdb btop` (macos): `lldb btop`

2. `r` to run, wait for crash and press enter if prompted, CTRL+L to clear screen if needed.

3. (gdb): `thread apply all bt` (lldb): `bt all` to get backtrace for all threads

4. Copy and paste the backtrace here:

**Comment by aristocratos** [comment]
@bphd You need to actually fill in the bug report form if you expect to get any help...

**Comment by bphd** [comment]
Done

**Comment by aristocratos** [comment]
> Latest arch; latest community; all default; all terminals; x64

"Latest arch" is not a version number and changes when arch changes version...
"all default" what is all default. And default regarding to what? Arch? Defaults also change...
"x64" there are alot of 64-bit architectures, (x86_64, aarch64, etc.)

Some useful information might also be how much is "Way too much cores", how many cores do you have?
What Cpu do you have?
Are all you cpu cores online?
Are you running virtualized?

Could you also post the output of `cat /proc/stat` and `cat /proc/cpuinfo`?

**Comment by bphd** [comment]
It's a rolling release, good luck getting any version

Default about software configuration, I just installed it, modified nothing

https://en.wikipedia.org/wiki/X64

The cores that I have are the ones that you see having activity on the screenshot, the ones that I don't are the one who hasn't

All my cores are activated and it work just fine (for information, on BPYTop it displays just fine the right number)

I'm bare metal on host

**Comment by aristocratos** [comment]
> Latest arch; latest community; (It's a rolling release, good luck getting any version)

I'm interested in the btop version not your version of arch...

The information section in the bug report:
>btop++ version: btop -v
Binary: [self compiled or static binary from release]
(If compiled) Compiler and version:
Architecture: [x86_64, aarch64, etc.] uname -m
Platform: [Linux, FreeBSD, OsX]
(Linux) Kernel: uname -r
(OSX/FreeBSD) Os release version:
Terminal used:
Font used:

Is not because I'm curious about you, but because it helps narrow down where the issue might originate and also as a reference if someone running an older version of btop in the future have similar issues.

> Could you also post the output of cat /proc/stat and cat /proc/cpuinfo?

This is a open-source issue tracker, not a personal tech support page. If your not willing to help debug the issue yourself, I don't think I am either.

**Comment by bphd** [comment]
Like I said "[latest community](https://repology.org/project/btop/versions)"

**Comment by aristocratos** [comment]
> Like I said "[latest community](https://repology.org/project/btop/versions)"

And which version will this link to in 2 months time when someone else looks at this issue and there have been 2 new releases?

**Comment by bphd** [comment]
Dunno, but he can look what has been released two months ago

**Comment by aristocratos** [comment]
Or you could just write which version you are using and save everyone the trouble?

**Comment by aristocratos** [comment]
I believe this change is the issue https://github.com/aristocratos/btop/commit/e5cc895015101a2fd0160bb0816da8dff3129699
For some reason your kernel reports 16 instead of the expected value of 2 for a 2 core system.
Should be fixed by reverting the core count method and letting the newly added dynamic core count update fix any issues on systems with cores not online.
Test with latest commit or download binary from https://github.com/aristocratos/btop/actions/runs/3240444400 when it's done running.

**Comment by bphd** [comment]
It's not completed as long as it hasn't been validated after testing

**Comment by aristocratos** [comment]
Github would tell you different:
> [aristocratos](https://github.com/aristocratos) closed this as [completed](https://github.com/aristocratos/btop/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [33 minutes ago](https://github.com/aristocratos/btop/issues/445#event-7579964874)

I'm gonna go ahead and trust my self on this one.

**Comment by bphd** [comment]
I don't know how it went but the update (v1.2.12) seems to have streamed down today on my computer, I guess. So I have only two cores listed like it was on BpyTop. So thanks, it's all right now. But from my perspective it can only be closed now, now that it was tested in production by actual users via conventional canals, it can really be resolved

**Comment by aristocratos** [comment]
> But from my perspective it can only be closed now, now that it was tested in production by actual users via conventional canals, it can really be resolved

Why would your perspective on when a issue should be closed have any sway in my github repository?
There is no "production", "conventional canals" or product for sale here.
You're not a customer, but a user of open-source software, you're not entitled to anything.
How developers respond to you (if they do) will be directly correlated to how you come across...

I gave you the means to test the fix 23 days ago which you ignored:
>[aristocratos](https://github.com/aristocratos) commented [23 days ago](https://github.com/aristocratos/btop/issues/445#issuecomment-1277155294)
> Test with latest commit or download binary from https://github.com/aristocratos/btop/actions/runs/3240444400 when it's done running.

I closed the issue because I fixed the issue, simple as that.

**Comment by bphd** [comment]
I didn't want to compile on such platform to test such commit etc... I wanted the problem to be corrected for all "normal" users. Thats the major reason why I want to report the problem. If it was just up to me I could live with any non critical problems, or even just switch to something else for critical ones

But sorry if you felt offended by this conversation, it wasn't meant to. I don't have professional needs, I just wanted the problem to be resolved for most of people, which can sometimes be similar to office methods

Thanks for your work, it's neat, and the whole refactoring in C just for the sake of it is really much appreciated and "bloatless" lol

Have a great day

**Comment by aristocratos** [comment]
> I didn't want to compile on such platform to test such commit etc...

That's why I linked to the build for the commit https://github.com/aristocratos/btop/actions/runs/3240444400 which has binaries at the bottom of the page including for your platform.

> But sorry if you felt offended by this conversation, it wasn't meant to.

I'm not offended, it's just a bit annoying to get bug reports where the requested information isn't filled in and I have to repeatedly ask to get relevant information

> Thanks for your work, it's neat, [..]
> Have a great day

No problem, have a great day yourself!
