### ISSUE TITLE
[REQUEST] Testing of compilers other than GCC

### ISSUE THREAD

**Issue by td5038** [aristocratos/btop#561]
**Is your feature request related to a problem? Please describe.**
It f***ing bugs me that the docs say you need GCC when Clang works perfectly, confusing Gentoo maintainers.

**Describe the solution you'd like**
I would like more compilers to be tested for btop++

**Describe alternatives you've considered**

**Additional context**

**Comment by aristocratos** [comment]
@td5038 
> It f***ing bugs me that the docs say you need GCC when Clang works perfectly, confusing Gentoo maintainers.

It fucking bugs me when people complain when having done zero research into their complaints...

Is it confusing to you that the documentation isn't updated in realtime for which new compiler releases now has C++20 support?

Support for clang (and only clang 16 mind you) was literally added last week: #510

The reason (mentioned several times in all threads related to compiler support) is because the lacking support for C++20 in many compilers with the exception of gcc 10+ (and now clang 16).

> I would like more compilers to be tested for btop++

No one is stopping you from testing any compiler you want. Good luck with that. Or are you expecting someone else to this for you? If so, why?

Most developers on github are doing this in their spare time, and so am I, solely because I think it's fun. If Gentoo maintainers are confused or not, aren't really something I even think about, since I'm not really beholden to manage the confusion for anyone but myself (which is fairly regularly anyways). 

Good look to you and report back if you find some random c++ compiler that supports c++20 and can compile btop.

**Comment by td5038** [comment]
Well, I tested building with Clang and it spat out a working binary.
