### ISSUE TITLE
[BUG] rocm_smi_lib structs has changed on ROCm 6, causing segmentation fault

### ISSUE THREAD

**Issue by fxzjshm** [aristocratos/btop#705]
**Describe the bug**

The definition of struct `rsmi_frequencies_t` has changed on ROCm 6,
but `Gpu::Rsmi::rsmi_frequencies_t` is the ROCm 5.x one, causing segmentation fault.
( [`rsmi_frequencies_t` of ROCm 6.0.0](https://rocm.docs.amd.com/projects/rocm_smi_lib/en/docs-6.0.0/.doxygen/docBin/html/structrsmi__frequencies__t.html), [`rsmi_frequencies_t` of ROCm 5.7.1](https://rocm.docs.amd.com/projects/rocm_smi_lib/en/docs-5.7.1/.doxygen/docBin/html/structrsmi__frequencies__t.html) )

Fix seems simple: replace the definition; 
but if need to check this on compile, maybe have to always `#include <rocm_smi/rocm_smi.h>` instead of `#if defined(RSMI_STATIC)`

Workaround: build and link the ROCm SMI library statically.

**To Reproduce**
* Install ROCm 6
* build btop with GPU support and without building and linking the ROCm SMI library statically
* run btop

**Expected behavior**
* work normally

**Screenshots**
```
[1]    157114 segmentation fault (core dumped)  ./btop
```

**Info (please complete the following information):**
 - btop++ version: 1.3.0 `36842a3`
 - Binary: self compiled
 - (If compiled) Compiler and version: g++ 11.4.0 & clang 17.0.4
 - Architecture: x86_64
 - Platform: Linux
 - (Linux) Kernel: 6.5.0-1010-oem
 - Terminal used: Konsole 22.04.3
 - Font used: Noto Mono

**Additional context**

Contents of `~/.config/btop/btop.log`
```
2024/01/08 (00:56:59) | ===> btop++ v.1.3.0
2024/01/08 (00:56:59) | WARNING: ROCm SMI: Failed to get maximum GPU power draw, defaulting to 225W
2024/01/08 (00:56:59) | WARNING: ROCm SMI: Failed to get maximum GPU temperature, defaulting to 110°C
2024/01/08 (00:56:59) | WARNING: ROCm SMI: Failed to get VRAM utilization
```

**GDB Backtrace**

(Extra helpful if compiled with `make OPTFLAGS="-O0 -g"`)
```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x0000000000000000 in ?? ()
(gdb) 
```
Even with `OPTFLAGS="-O0 -g"`

**Comment by alerque** [comment]
This is immanently about to break `btop` on a bunch of distros. Because of the way it is compiled where it isn't even linked to the ROCm libraries but does try to load them at runtime if found, the `btop` packages are not even getting marked to be rebuilt and tested with ROCm 6 — which is about to land in several distros. This will break the existing `btop` binaries as currently installed.

I think some sort of defensive move needs to happen soon. Either it needs to be made compatible with the v6 API so it can run or at least the version needs to be checked for compatibly and ignored if it is not compatible so at least it doesn't crash.

**Comment by Rikj000** [comment]
> This is immanently about to break btop on a bunch of distros.

Can confirm that btop is already broken on Manjaro due to this bug.

**Comment by aristocratos** [comment]
@fxzjshm @alerque 
Btop is not built statically with ROCm *unless manually instructed to*. And the manual defintion of `rsmi_frequencies_t` is only relevant when statically linking.

Not sure why it's manually defined though, @romner-set ?

Regardless it's mentioned in the GPU section of the readme that static linking is only tested working with ROCm 5.6.x.

> btop++ is statically linked to ROCm SMI with the RSMI_STATIC=true make flag.

> This flag expects the ROCm SMI source code in lib/rocm_smi_lib, and compilation will fail if it's not there. The latest tested version is 5.6.x

This shouldn't be an issue when dynamic linking ROCm (which is the default).

@Rikj000
Create a bug report if it's not working, without knowing you or you're expertise in the matter I can't really take your word for it without more information.

**Comment by alerque** [comment]
The issue here is for packages built **without** static linking or ROCm even present at build time. I'm the Arch Linux packager for btop and we have reports of our current btop package crashing when compiled with people installing ROCm 6. The btop package is *not* built with any special options (just `make all`). Just adding `rocm-smi-lib` >=6 packages onto the system is apparently causing segfaults [per this downstream issue](https://gitlab.archlinux.org/archlinux/packaging/packages/btop/-/issues/2).

**Comment by aristocratos** [comment]
@alerque 
Well that's bad.

I'm gusseing for dynamic linking ROCm to work there would need to be a new specific version of the binary whenever AMD decides to change the ABI.

Since if (as right now) the binary isn't locked to a specific ROCm version, it will break again eventually.

**Comment by alerque** [comment]
> I'm gusseing for dynamic linking ROCm to work there would need to be a new specific version of the binary whenever AMD decides to change the ABI.

Perhaps, but something else is fishy to me. It isn't even clear to me that standard dynamic linking is going on. If there was it should show up in a scan for linked modules, and also the shared module or headers would need to be available at build time. That isn't the case here, we're building in a chroot **without** rocm. The result is a binary that works fine on it's own. There appears to be some sort of runtime check for if the libraries exists and if it does it tries to use it. That makes GPU support work or not work based on whether another package is installed or not.

The missing piece seems to be that the library is not actually dynamically linked, some sort of blind assumption is made about what would be called if found at run time. As such it segfaults if the library exists but isn't the expected ABI.

I would suggest there needs to be some sort of runtime and/or build time check for ABI compatibility. A 5/6 flag at build time would do the trick for us. Also just an on-off flag that could disable the runtime usage at build time would work to fix the crash while we wait for 6 support.

**Comment by aristocratos** [comment]
@alerque @fxzjshm 
I pushed some changes to check the version of ROCm loaded and select correct definition: 55111315723d3773ea2a8235c294e33d0a66eaf1

It should also disable AMD gpu support if ROCm version is less than 5 or greater than 6 now.

It compiles alright, but I don't have AMD hardware to test on.
Do you guys wanna compile from latest commit and see how it goes?

**Comment by romner-set** [comment]
> Btop is not built statically with ROCm _unless manually instructed to_. And the manual defintion of `rsmi_frequencies_t` is only relevant when statically linking.
> 
> Not sure why it's manually defined though, @romner-set ?

@aristocratos  Looking back at the commits, I'm pretty sure it's so that it's possible to dynamically load and use RSMI even if `lib/rocm_smi_lib` is not available at compile time.

Being able to implement more versions of the ABI is also possible as you're doing right now, however I think it may be better to just drop all of the manual definitions, include the header file as it's being done with static linking, and always use the latest RSMI ABI with a hard "you must have `lib/rocm_smi_lib` pulled if you want any kind of AMDGPU support". Implementing branches for every new version will likely lead to very messy code, very quickly. It's your call though.

This solution will still require checks in case RSMI gets updated faster than btop can roll out a patch, but that's the best I can come up with (apart from packagers always compiling a statically linked version, which would likely solve all of these problems).

**Comment by romner-set** [comment]
Also @alerque, just to clear up some confusion: it's being dynamically loaded, not linked. IIRC It's done this way so that a binary compiled with RSMI support can be used on an NVIDIA-only system without installing a useless dependency.

**Comment by aristocratos** [comment]
@romner-set
> I'm pretty sure it's so that it's possible to dynamically load and use RSMI even if lib/rocm_smi_lib is not available at compile time.

Yeah, I realized when I started looking at the code, had forgotten.

> however I think it may be better to just drop all of the manual definitions, include the header file as it's being done with static linking, and always use the latest RSMI ABI with a hard "you must have lib/rocm_smi_lib pulled if you want any kind of AMDGPU support". 

I don't think it's a big issue *yet*. The only difference between version 5 and 6 for the functionality we use were only an added bool in a struct.
As long as they stick with only breaking ABI between major versions I don't mind adding some branches when needed.

And the code I added will disable AMD gpu support instead of crashing if using an unsupported ROCm version, unless in the unlikely case that they change the definition for `rsmi_version_get()`...

**Comment by fxzjshm** [comment]
@aristocratos I've tested the commit 5511131 and made some further changes at #737 , after applying these changes it seems to work on my setup.

**Comment by alerque** [comment]
We just had to disable GPU support entirely in btop on Arch Linux because ROCM6 shipped before a release was cut with this fix. I'll re-enable it as soon as a release is cut.

**Comment by aristocratos** [comment]
@alerque Fixes included in release [v1.3.1](https://github.com/aristocratos/btop/releases/tag/v1.3.1)

**Comment by ecksun** [comment]
A (somewhat limited) workaround for distributions still using old versions of btop (like debian) is to use firejail:

    firejail --blacklist=/usr/lib/x86_64-linux-gnu/librocm_smi64.so.1.0 btop

(I found the library with `dpkg -L librocm-smi64-1`)

Edit: [1.3.2 is now in sid](https://packages.debian.org/sid/btop)

**Comment by quill-g** [comment]
this really sucks for debian users, any real solution for us?

**Comment by kmanwar89** [comment]
Just chiming in to confirm this behavior is affecting my P14s Gen 5 w/ AMD Ryzen AI after installing ROCm, as mentioned above. `btop` was working immediately prior to installing ROCm. 

Ubuntu 24.04.2 is installing v1.3.0-1 in the repositories, but it looks like 1.3.1 was released last year - did it ever make its way into the repos?

I downloaded the 1.4.3 release from [here](https://github.com/aristocratos/btop/releases/tag/v1.4.3), un-tar'd it (`tar -xjf <filename.tbz>`) and then ran `install.sh` within the `btop` folder. This copied the binary to `/usr/local/bin/btop`.

Running `btop -v` shows v1.4.3, and no issues on my ROCm-enabled AMD machine now!
