### ISSUE TITLE
zen per core temp fix

### ISSUE THREAD

**Issue by 1188ws** [aristocratos/btop#93]
amd 4000 series laptop temp fix

cpu temp dont work

amd 4000  series

cpu temp work 

![Screenshot from 2021-10-17 09-33-50](https://user-images.githubusercontent.com/88446371/137614700-ea1f8caa-74b6-4c5b-8bbe-61cb15831bf6.png)

![Screenshot from 2021-10-17 09-05-03](https://user-images.githubusercontent.com/88446371/137614708-1cef3b5e-1fe7-4243-9d0e-f2d76e54db63.png)

 - btop++ v1.0.0-1.0.15
 self compiled 
 - Architecture x86_64,
 - Platform: Linux
 - (Linux) Kernel: 5.11.0-37-generic
 - Terminal used: gnome terminal
 - Font used:  - gnome Font

**Additional context**

[error.log](https://github.com/aristocratos/btop/files/7358918/error.log)

add per core temp 
![Screenshot from 2021-10-17 09-52-26](https://user-images.githubusercontent.com/88446371/137615365-e1b0caac-2332-44ca-9925-63a9a9530331.png)

vs

![Screenshot from 2021-10-17 09-57-46](https://user-images.githubusercontent.com/88446371/137615439-d24a0cb0-5a93-4e6a-a321-118fb7396e3f.png)

**Comment by aristocratos** [comment]
@1188ws 
> cpu temp dont work

Btop can't autodetect your cpu sensor on ryzen mobile since it's not reporting a sensor called "cpu". You can choose a sensor corresponding to your cpu temp in the menu.

> add per core temp

Tell amd to do so. The chipset isn't reporting any temps.

Your "error.log" is from bpytop and not the "btop.log" from btop++.
If you look in the correct log file I think you would see a warning:
"No good candidate for cpu sensor found, using random from all found sensors.".
